### ISSUE TITLE
Live streaming unavailable

### ISSUE THREAD

**Issue by tes5884** [jitsi/jibri#92] opened 2018-04-30 16:28 UTC
I'm getting the following error, any suggestions which parameter is missing?
```
2018-04-30 12:26:01.049 INFO: [1] org.jitsi.jibri.Main.main() Using config file /etc/jitsi/jibri/config.json
2018-04-30 12:26:02.784 SEVERE: [1] org.jitsi.jibri.Main.error() A required config parameter was missing: Instantiation of [simple type, class org.jitsi.jibri.config.XmppEnvironmentConfig] value failed for JSON property name due to missing (therefore NULL) value for creator parameter name which is a non-nullable type
```

**Comment by tes5884** [comment] 2018-04-30 16:30
Here is my config: 
```
{
    "recording_directory":"/tmp/recordings",
    // The path to the script which will be run on completed recordings
    "finalize_recording_script_path": "/path/to/finalize_recording.sh",
    "xmpp_environments": [
        {
            "name": "prod environment",
            // The hosts of the XMPP servers to connect to as part of
            //  this environment
            "xmpp_server_hosts": [
                "prod.xmpp.my.domain.com"
            ],
            // The xmpp domain we'll connect to on the XMPP server
            "xmpp_domain": "xmpp.my.domain.com",
            // Jibri will login to the xmpp server as a privileged user
            "control_login": {
                // The domain to use for logging in
                "domain": "auth.xmpp.my.domain.com",
                // The credentials for logging in
                "username": "jibri",
                "password": "my.password.here"
            },
            // Using the control_login information above, Jibri will join
            //  a control muc as a means of announcing its availability
            //  to provide services for a given environment
            "control_muc": {
                "domain": "internal.auth.xmpp.my.domain.com",
                "room_name": "JibriBrewery",
                "nickname": "jibri-nickname"
            },
            // All participants in a call join a muc so they can exchange
            //  information.  Jibri can be instructed to join a special muc
            //  with credentials to give it special abilities (e.g. not being
            //  displayed to other users like a normal participant)
            "call_login": {
                "domain": "recorder.xmpp.my.domain.com",
                "username": "recorder",
                "password": "my.password.here"
            },
            // When jibri gets a request to start a service for a room, the room
            //  jid will look like:
            //  roomName@optional.prefixes.subdomain.xmpp_domain
            // We'll build the url for the call by transforming that into:
            //  https://xmpp_domain/subdomain/roomName
            // So if there are any prefixes in the jid (like jitsi meet, which
            //  has its participants join a muc at conference.xmpp_domain) then
            //  list that prefix here so it can be stripped out to generate
            //  the call url correctly
            "room_jid_domain_string_to_strip_from_start": "conference.",
            "usage_timeout": "0"
        },
        {
        }
    ]
}
```

**Comment by bbaldino** [comment] 2018-04-30 16:38
Hey @tes5884, I think the issue is the empty object you have at the bottom there:
```
            ...<snip>...
            "room_jid_domain_string_to_strip_from_start": "conference.",
            "usage_timeout": "0"
        },
        {
        }
    ]
```
The config parser will see the second entry and expect to be able to parse it as an XmppEnvironmentConfig, but since it's empty it'll fail.  Try just removing that and see if it works.

**Comment by tes5884** [comment] 2018-04-30 16:47
Thanks for the tip! I removed that line, and the logs aren't showing anything now. But I'm still getting 'Live streaming unavailable'.

Any suggestions on how to get more logging? or where to look..

Thanks

**Comment by bbaldino** [comment] 2018-04-30 17:12
If you're getting 'Live streaming unavailable' it probably means that Jicofo isn't seeing the Jibri.  Did you do the brewery config in the Jicofo config file?  https://github.com/jitsi/jibri#jicofo

**Comment by tes5884** [comment] 2018-04-30 17:24
I fixed that. What belongs on line 17 [here](https://github.com/jitsi/jibri/blob/master/resources/debian-package/etc/jitsi/jibri/config.json)

**Comment by bbaldino** [comment] 2018-04-30 17:33
That's the network hostname of the server hosting your xmpp server.

**Comment by tes5884** [comment] 2018-04-30 17:44
Updated xmpp server hostname, as well as corrected the Jicofo settings. Still getting "Live streaming unavailable" and nothing in the logs.. Where can I look next?

**Comment by aaronkvanmeerten** [comment] 2018-04-30 17:48
Jicofo logs should show the following when jibri brewery is enabled:

Jicofo 2018-04-26 16:42:56.334 INFO: [1] org.jitsi.impl.configuration.ConfigurationServiceImpl.log() org.jitsi.jicofo.jibri.BREWERY=JibriBrewery@internal.auth.my.domain.com

If you don't see that, then you'll want to restart jicofo with the new settings enabled and see if it's visible.  If not, you may need to check prosody configuration too, to ensure internal.auth.my.domain.com is set up as a separate conference MUC in prosody.

Jicofo logs should have something like the following when Jicofo detects a new jibri:

Jicofo 2018-04-26 22:41:05.391 INFO: [38] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().168 Jibri: jibribrewery@internal.auth.my.domain.com/jibri17487 available: true


If you don't see this, check in the jibri logs, in /var/log/jitsi/jibri/* and see whether you see any connection failed errors, certificate rejection errors or anything else that might explain why the connection is failing.

**Comment by tes5884** [comment] 2018-04-30 18:15
I think I have the different domains confused in config.json.

So when to use recorder.my.domain when to use conference.my.domain etc? the old jibri had a little better documentation in that regard. Where do I use which domain?

**Comment by tes5884** [comment] 2018-04-30 18:27
> Here is the login for the control muc itself. For a normal Jicofo deploy this is "internal.auth.main.xmpp.domain"

It looks like I'm having trouble with the part above. Where can I find the corresponding domain on the jitsi server? is that in prosody or jicofo? 
I would think in prosody, but the virtual domain there has recorder.my.domain listed

**Comment by tes5884** [comment] 2018-04-30 18:30
in my jitsi config I have: `muc: conference.my.domain`

**Comment by aaronkvanmeerten** [comment] 2018-04-30 18:30
I just reviewed the README and I see part of the issue is that we haven't made the appropriate recommendation for the internal.auth prosody domain.  I'm updating the instructions now, but what you'll want is a prosody configuration stanza like so:

-- internal muc component, meant to enable pools of jibri and jigasi clients
Component "internal.auth.my.domain.com "muc"
    modules_enabled = {
      "ping";
    }
    storage = "null"
    muc_room_cache_size = 1000

**Comment by tes5884** [comment] 2018-04-30 18:31
> Component "internal.auth.my.domain.com "muc"
Are those quotes accurate?

**Comment by aaronkvanmeerten** [comment] 2018-04-30 18:32
Not sure what happened during my copy/paste, but I've adjusted it now.  I can confirm that the copied string DID have all the correct " so maybe it's the markdown editor.  Anyway, there's the appropriate value set now.

**Comment by tes5884** [comment] 2018-04-30 18:33
Is this in addition to my VirtualHost "recorder.mydomain" ?

**Comment by aaronkvanmeerten** [comment] 2018-04-30 18:34
Correct.  The VirtualHost there is in place to hold the recorder@recorder.mydomain user entry, so that the chrome user can log in successfully and be "hidden" from other users.
The muc component here is to allow all the jibris to be discovered/used in a MUC that's never accessible via video conferences.  So we create a separate MUC to allow the jibris to be discovered by jicofo without risking users accidentally or intentionally joining this MUC via the jitsi-meet client.

**Comment by tes5884** [comment] 2018-04-30 18:38
Jibri logs show authenticated. Still getting the Live stream error.
Jicofo logs show the following:
`INFO: [57] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Publish new JIBRI status: <jibri-recording-status xmlns='http://jitsi.org/protocol/jibri' status='undefined'/>`

Is that meaningful?

**Comment by tes5884** [comment] 2018-04-30 18:39
Once I get this figured out, I'll submit a PR with my attempt at improving the docs... FWIW

**Comment by aaronkvanmeerten** [comment] 2018-04-30 18:42
Thanks.  I've also made a new PR with a stab at improving them too.

https://github.com/jitsi/jibri/pull/93

**Comment by aaronkvanmeerten** [comment] 2018-04-30 18:43
the Jibri "undefined" status means that the Jicofo is telling the room that there are no Jibri instances available.  Can you see where the notifyJibriStatus shows up with your jibri connecting to jicofo?

**Comment by tes5884** [comment] 2018-04-30 18:45
>  Can you see where the notifyJibriStatus shows up with your jibri connecting to jicofo?

I don't understand that part, can you please explain?

**Comment by aaronkvanmeerten** [comment] 2018-04-30 18:47
Sure.  What I'm asking is if you see the equivalent line to mine from above?

org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().168 Jibri: jibribrewery@internal.auth.my.domain.com/jibri17487 available: true

If so, then you should have also seen this:

Jicofo 2018-04-26 22:41:05.397 INFO: [38] org.jitsi.jicofo.xmpp.BaseBrewery.processInstanceStatusChanged().302 Added brewery instance: jibribrewery@internal.auth.my.domain.com/jibri17487


If you aren't seeing those type of lines in the jicofo logs, then your jibri isn't actually connecting successfully, or jicofo isn't discovering it successfully.

**Comment by tes5884** [comment] 2018-04-30 18:50
I'm not seeing that at all (according to grep)
I'm seeing this error in Jibri logs, is it significant?
`2018-04-30 14:36:52.703 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored.`

**Comment by tes5884** [comment] 2018-04-30 18:52
I really appreciate your guys helping out!!! We had a 3 jitsi streams with close to 1000 people watching that was being streamed using OBS last year, I'm trying to get Jibri working, so I don't need to use OBS.

**Comment by aaronkvanmeerten** [comment] 2018-04-30 18:56
I actually see the same thing on a working Jibri so it may just be an error but not a fatal one.  I'll ask @bbaldino to weigh in on that.  However, here's what a working jibri log looks like.

`
2018-04-26 16:48:50.866 INFO: [1] org.jitsi.jibri.Main.main() Using config file /etc/jitsi/jibri/config.json
2018-04-26 16:48:51.827 INFO: [1] org.jitsi.jibri.Main.loadConfig() Parsed config:
JibriConfig(recordingDirectory=/tmp/recordings, finalizeRecordingScriptPath=/usr/local/bin/finalize_recording.sh, xmppEnvironments=[XmppEnvironmentConfig(name=hcv-atlasjitsi, xmppServerHosts=[54.152.188.80, 54.166.208.1, 54.
144.245.71, 18.232.115.213, 18.232.101.142], xmppDomain=my.domain.com, controlLogin=XmppCredentials(domain=auth.my.domain.com, username=jibri, password=j1br1), controlMuc=XmppMuc(domain=internal.auth.my.domain.com, roomName=JibriBrewery, nickname=jibri17487), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.my.domain.com, username=recorder, password=mypassword), stripFromRoomDomain=conference., usageTi
meoutMins=0, trustAllXmppCerts=true)])
2018-04-26 16:48:52.190 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.internal.InternalHttpApi registered in SERVER runtime does not implement any prov
ider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.internal.InternalHttpApi will be ignored.
2018-04-26 16:48:52.429 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Connecting to xmpp environment on 54.152.188.80 with config XmppEnvironmentConfig(name=hcv-atlasjitsi, xmppServerHosts=[54.152.188.80, 54.166.208.1,
54.144.245.71, 18.232.115.213, 18.232.101.142], xmppDomain=my.domain.com, controlLogin=XmppCredentials(domain=auth.my.domain.com, username=jibri, password=j1br1), controlMuc=XmppMuc(domain=internal.auth.my.domain.com, roomName=JibriBrewery, nickname=jibri17487), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.my.domain.com, username=recorder, password=mypassword), stripFromRoomDomain=conference., usag
eTimeoutMins=0, trustAllXmppCerts=true)
2018-04-26 16:48:52.437 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
2018-04-26 16:48:52.681 INFO: [1] class org.jitsi.xmpp.mucclient.MucClient.connected() Xmpp connection status [auth.my.domain.com]: connected
2018-04-26 16:48:52.764 INFO: [1] class org.jitsi.xmpp.mucclient.MucClient.authenticated() Xmpp connection status [auth.my.domain.com]: authenticated
2018-04-26 16:48:52.796 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Connecting to xmpp environment on 54.166.208.1 with config XmppEnvironmentConfig(name=hcv-atlasjitsi, xmppServerHosts=[54.152.188.80, 54.166.208.1, 5
4.144.245.71, 18.232.115.213, 18.232.101.142], xmppDomain=my.domain.com, controlLogin=XmppCredentials(domain=auth.my.domain.com, username=jibri, password=j1br1), controlMuc=XmppMuc(domain=internal.auth.my.domain.com
, roomName=JibriBrewery, nickname=jibri17487), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.my.domain.com, username=recorder, password=mypassword), stripFromRoomDomain=conference., usage
TimeoutMins=0, trustAllXmppCerts=true)




2018-04-26 16:49:01.846 FINE: [69] org.jitsi.jibri.api.http.HttpApi.debug() Got health request
`

**Comment by tes5884** [comment] 2018-04-30 19:03
Logs aren't helping me. My configs are all below. If you guys can look, I'd appreciate it!

[Jitsi config](https://fnpaste.com/LPRk)
[Jicofo](https://fnpaste.com/xRpE)
[Prosody](https://fnpaste.com/pNyn)
[Jibri](https://fnpaste.com/6L3E)

**Comment by bbaldino** [comment] 2018-04-30 20:56
> I'm not seeing that at all (according to grep)
> I'm seeing this error in Jibri logs, is it significant?
> 2018-04-30 14:36:52.703 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored.

Yeah you can ignore this.  I've tried to get rid of these (I hate warnings/errors that print but actually aren't real issues), but it's a [Jersey thing](https://github.com/jersey/jersey/issues/3700) and I'm not sure there's a good way to get rid of it yet.

**Comment by bbaldino** [comment] 2018-04-30 20:57
@tes5884 Can you include the Jicofo logs?

**Comment by aaronkvanmeerten** [comment] 2018-04-30 20:58
You have misconfigured Jicofo to search for jibri in the conference MUC

You have:
org.jitsi.jicofo.jibri.BREWERY=JibriBrewery@conference.jitsi.tscinc.co

You want:
 org.jitsi.jicofo.jibri.BREWERY=JibriBrewery@internal.auth.jitsi.tscinc.co

**Comment by tes5884** [comment] 2018-04-30 21:06
BAM! That seems to have worked! It worked for a few minutes, and then disconnected. I'm going to test it a bit more.

**Comment by bbaldino** [comment] 2018-04-30 21:12
@tes5884 👍 

you can paste Jibri logs here if you are still running into the disconnection issue.

**Comment by bbaldino** [comment] 2018-04-30 21:13
closing the issue but feel free to post logs here or the mailing list or open a new issue if you run into anything.

**Comment by tes5884** [comment] 2018-04-30 21:14
Thank you guys for all the help!

**Closed by bbaldino** 2018-04-30 21:13 UTC

**Comment by bassim69** [comment] 2018-05-19 23:02
I have same problem
May 20 02:02:00 meet systemd[1]: Stopping Jibri Process...
May 20 02:02:00 meet graceful_shutdown.sh[6830]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
May 20 02:02:00 meet graceful_shutdown.sh[6830]:                                  Dload  Upload   Total   Spent    Left  Speed
May 20 02:02:00 meet launch.sh[6581]: 2018-05-20 02:02:00.839 INFO: [13] org.jitsi.jibri.api.http.internal.InternalHttpApi.gracefulShutdown() Jibri gracefully shutting down
May 20 02:02:00 meet graceful_shutdown.sh[6830]: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
May 20 02:02:01 meet systemd[1]: jibri.service: Main process exited, code=exited, status=143/n/a
May 20 02:02:01 meet systemd[1]: jibri.service: Failed with result 'exit-code'.
May 20 02:02:01 meet systemd[1]: Stopped Jibri Process.
May 20 02:02:01 meet systemd[1]: Started Jibri Process.
May 20 02:02:01 meet launch.sh[6836]: 2018-05-20 02:02:01.438 INFO: [1] org.jitsi.jibri.Main.main() Using config file /etc/jitsi/jibri/config.json
May 20 02:02:02 meet launch.sh[6836]: 2018-05-20 02:02:02.303 INFO: [1] org.jitsi.jibri.Main.loadConfig() Parsed config:
May 20 02:02:02 meet launch.sh[6836]: JibriConfig(recordingDirectory=/tmp/recordings, finalizeRecordingScriptPath=/home/jibri/jibri/resources/finalize_recording.sh, xmppEnvironments=[XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[meet.realtime-tec.com], xmppDomain=meet.realtime-tec.com, controlLogin=XmppCredentials(domain=auth.meet.realtime-tec.com, username=jitsi, password=pvtP@ssw0rd), controlMuc=XmppMuc(domain=internal.auth.meet.realtime-tec.com, roomName=JibriBrewery, nickname=jibri), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.meet.realtime-tec.com, username=recorder, password=pvtP@ssw0rd), stripFromRoomDomain=conference., usageTimeoutMins=0, trustAllXmppCerts=true)])
May 20 02:02:02 meet launch.sh[6836]: 2018-05-20 02:02:02.359:INFO::main: Logging initialized @1158ms
May 20 02:02:02 meet launch.sh[6836]: 2018-05-20 02:02:02.401:WARN:oejsh.ContextHandler:main: o.e.j.s.ServletContextHandler@7b420819{/,null,null} contextPath ends with /*
May 20 02:02:02 meet launch.sh[6836]: 2018-05-20 02:02:02.401:WARN:oejsh.ContextHandler:main: Empty contextPath
May 20 02:02:02 meet launch.sh[6836]: 2018-05-20 02:02:02.405:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
May 20 02:02:02 meet launch.sh[6836]: 2018-05-20 02:02:02.898 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.internal.InternalHttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.internal.InternalHttpApi will be ignored.
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.108:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@7b420819{/,null,AVAILABLE}
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.126:INFO:oejs.ServerConnector:main: Started ServerConnector@7180a45b{HTTP/1.1}{0.0.0.0:3333}
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.127:INFO:oejs.Server:main: Started @1926ms
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.325 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Connecting to xmpp environment on meet.realtime-tec.com with config XmppEnvironmentConfig(name=prod environment, xmppServerHosts=[meet.realtime-tec.com], xmppDomain=meet.realtime-tec.com, controlLogin=XmppCredentials(domain=auth.meet.realtime-tec.com, username=jitsi, password=pvtP@ssw0rd), controlMuc=XmppMuc(domain=internal.auth.meet.realtime-tec.com, roomName=JibriBrewery, nickname=jibri), sipControlMuc=null, callLogin=XmppCredentials(domain=recorder.meet.realtime-tec.com, username=recorder, password=pvtP@ssw0rd), stripFromRoomDomain=conference., usageTimeoutMins=0, trustAllXmppCerts=true)
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.339 INFO: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() The trustAllXmppCerts config is enabled for this domain, all XMPP server provided certificates will be accepted
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.844 INFO: [1] class org.jitsi.xmpp.mucclient.MucClient.connected() Xmpp connection status [auth.meet.realtime-tec.com]: connected
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.848 SEVERE: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Error connecting to xmpp environment: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.849:WARN:oejsh.ContextHandler:main: o.e.j.s.ServletContextHandler@7e46d648{/,null,null} contextPath ends with /*
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.850:WARN:oejsh.ContextHandler:main: Empty contextPath
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.850:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.915 WARNING: [1] org.glassfish.jersey.internal.inject.Providers.checkProviderRuntime() A provider org.jitsi.jibri.api.http.HttpApi registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.jitsi.jibri.api.http.HttpApi will be ignored.
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.969:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@7e46d648{/,null,AVAILABLE}
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.971:INFO:oejs.ServerConnector:main: Started ServerConnector@56799502{HTTP/1.1}{0.0.0.0:2222}
May 20 02:02:03 meet launch.sh[6836]: 2018-05-20 02:02:03.971:INFO:oejs.Server:main: Started @2771ms

**Comment by bbaldino** [comment] 2018-05-20 05:07
@bassim69 those logs show Jibri being shutdown and then started up, but nothing else.  Do you have logs which show an error?

**Comment by damencho** [comment] 2018-05-20 13:53
What about:
02:02:03.848 SEVERE: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Error connecting to xmpp environment: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized

**Comment by bbaldino** [comment] 2018-05-20 19:14
> What about:
> 02:02:03.848 SEVERE: [1] org.jitsi.jibri.api.xmpp.XmppApi.start() Error connecting to xmpp environment: org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized

Oops, sorry I missed that completely.  @damencho have you seen this with smack before?  I saw one issue for it but says it was fixed in 4.2.1 (which is the smack version Jibri uses).

**Comment by damencho** [comment] 2018-05-20 20:45
Isn't this just wrong username or password?

**Comment by CesarTavo** [comment] 2019-01-30 01:35
> Thank you guys for all the help!

How did you solve it?
